-- ============================================================
-- EduQuest ESAT Platform - Supabase Database Schema Script
-- Run this SQL in your Supabase SQL Editor (Dashboard > SQL Editor)
-- Dedicated, Isolated Schema for ESAT (Engineering and Science Admissions Test)
-- Idempotent & Re-runnable: Safe to execute multiple times
-- ============================================================

-- 1. Create Student Registration Table (esat_user)
CREATE TABLE IF NOT EXISTS public.esat_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    target_course TEXT DEFAULT 'Engineering',
    selected_modules TEXT[] DEFAULT ARRAY['Mathematics 1', 'Mathematics 2', 'Physics'],
    topic TEXT DEFAULT 'ESAT Assessment',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_esat_user_email ON public.esat_user(email);

-- Enable RLS for esat_user
ALTER TABLE public.esat_user ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert to esat_user" ON public.esat_user;
CREATE POLICY "Allow public insert to esat_user" ON public.esat_user FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public select from esat_user" ON public.esat_user;
CREATE POLICY "Allow public select from esat_user" ON public.esat_user FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public update to esat_user" ON public.esat_user;
CREATE POLICY "Allow public update to esat_user" ON public.esat_user FOR UPDATE USING (true);


-- 2. Create ESAT Modules Taxonomy Table (esat_modules)
CREATE TABLE IF NOT EXISTS public.esat_modules (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    code TEXT NOT NULL UNIQUE,
    is_compulsory BOOLEAN DEFAULT false,
    question_count INTEGER DEFAULT 27,
    duration_minutes INTEGER DEFAULT 40,
    icon TEXT DEFAULT '📐',
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed 5 Official ESAT Modules
INSERT INTO public.esat_modules (id, name, code, is_compulsory, question_count, duration_minutes, icon, description)
VALUES
    ('m1', 'Mathematics 1', 'MATH1', true, 27, 40, '📐', 'Compulsory module covering Pure Mathematics, Algebra, Geometry, Trigonometry, and Probability.'),
    ('m2', 'Mathematics 2', 'MATH2', false, 27, 40, '🔢', 'Advanced Pure Mathematics covering Calculus, Sequences, Coordinate Geometry, and Vectors.'),
    ('phys', 'Physics', 'PHYS', false, 27, 40, '⚡', 'Mechanics, Electricity, Waves, Optics, Thermal Physics, and Gravitational/Electric Fields.'),
    ('chem', 'Chemistry', 'CHEM', false, 27, 40, '🧪', 'Atomic Structure, Bonding, Energetics, Kinetics, Equilibria, Organic & Inorganic Chemistry.'),
    ('bio', 'Biology', 'BIO', false, 27, 40, '🧬', 'Cell Biology, Genetics, Evolution, Physiology, Plant Biology, and Ecology.')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    is_compulsory = EXCLUDED.is_compulsory,
    icon = EXCLUDED.icon,
    description = EXCLUDED.description;

ALTER TABLE public.esat_modules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select from esat_modules" ON public.esat_modules;
CREATE POLICY "Allow public select from esat_modules" ON public.esat_modules FOR SELECT USING (true);


-- 3. Create ESAT Question Bank Table (esat_questions)
CREATE TABLE IF NOT EXISTS public.esat_questions (
    id TEXT PRIMARY KEY,
    module_id TEXT REFERENCES public.esat_modules(id) ON DELETE RESTRICT,
    topic TEXT NOT NULL,
    subtopic TEXT,
    difficulty TEXT CHECK (difficulty IN ('Easy', 'Medium', 'Hard')) DEFAULT 'Medium',
    question TEXT NOT NULL,
    passage TEXT DEFAULT '',
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    option_e TEXT NOT NULL,
    correct_answer INTEGER CHECK (correct_answer >= 0 AND correct_answer <= 4) NOT NULL,
    explanation TEXT DEFAULT '',
    explanation_status TEXT CHECK (explanation_status IN ('complete', 'missing', 'needs_review')) DEFAULT 'complete',
    source_file TEXT,
    source_page INTEGER,
    source_question_number INTEGER,
    is_verified BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_esat_questions_module ON public.esat_questions(module_id);
CREATE INDEX IF NOT EXISTS idx_esat_questions_topic ON public.esat_questions(topic);
CREATE INDEX IF NOT EXISTS idx_esat_questions_diff ON public.esat_questions(difficulty);

ALTER TABLE public.esat_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select from esat_questions" ON public.esat_questions;
CREATE POLICY "Allow public select from esat_questions" ON public.esat_questions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow authenticated insert/update to esat_questions" ON public.esat_questions;
CREATE POLICY "Allow authenticated insert/update to esat_questions" ON public.esat_questions FOR ALL USING (true);


-- 4. Create ESAT Test Reports & Results Table (esat_report)
CREATE TABLE IF NOT EXISTS public.esat_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    test_title TEXT NOT NULL,
    test_type TEXT DEFAULT 'full_mock', -- 'full_mock', 'mock_test', 'diagnostic', 'topic_test'
    modules_taken TEXT[] DEFAULT ARRAY['Mathematics 1'],
    
    -- Overall Aggregate Metrics
    total_questions INTEGER NOT NULL DEFAULT 81,
    total_correct INTEGER NOT NULL DEFAULT 0,
    total_wrong INTEGER NOT NULL DEFAULT 0,
    total_unattempted INTEGER NOT NULL DEFAULT 0,
    overall_accuracy NUMERIC(5,2) DEFAULT 0.00,
    
    -- Module-wise Results JSON Array:
    -- [{"module": "Mathematics 1", "correct": 21, "total": 27, "wrong": 6, "unattempted": 0, "accuracy": 77.8, "esat_score": 6.8, "time_spent": "38:20"}, ...]
    module_scores_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    
    -- Topic-wise Breakdown JSON Array:
    -- [{"topic": "Algebra", "module": "Mathematics 1", "correct": 8, "total": 10, "pct": 80.0}, ...]
    topic_scores_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    
    -- Detailed Question-by-Question Review Logs
    answers_json JSONB DEFAULT '{}'::jsonb,
    details_json JSONB DEFAULT '[]'::jsonb,
    
    submit_time TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_esat_report_email ON public.esat_report(email);
CREATE INDEX IF NOT EXISTS idx_esat_report_test_type ON public.esat_report(test_type);
CREATE INDEX IF NOT EXISTS idx_esat_report_created_at ON public.esat_report(created_at DESC);

-- Enable RLS for esat_report
ALTER TABLE public.esat_report ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert to esat_report" ON public.esat_report;
CREATE POLICY "Allow public insert to esat_report" ON public.esat_report FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public select from esat_report" ON public.esat_report;
CREATE POLICY "Allow public select from esat_report" ON public.esat_report FOR SELECT USING (true);


-- 5. Create Course to ESAT Module Mapping Table (esat_course_requirements)
CREATE TABLE IF NOT EXISTS public.esat_course_requirements (
    id TEXT PRIMARY KEY,
    university TEXT NOT NULL,
    course_name TEXT NOT NULL,
    compulsory_module TEXT DEFAULT 'Mathematics 1',
    required_module_2 TEXT NOT NULL,
    required_module_3 TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO public.esat_course_requirements (id, university, course_name, compulsory_module, required_module_2, required_module_3, notes)
VALUES
    ('cam_eng', 'University of Cambridge', 'Engineering', 'Mathematics 1', 'Mathematics 2', 'Physics', 'Standard requirement for Engineering at Cambridge'),
    ('cam_natsci_phys', 'University of Cambridge', 'Natural Sciences (Physical)', 'Mathematics 1', 'Physics', 'Chemistry', 'Recommended for Physical Natural Sciences'),
    ('cam_natsci_bio', 'University of Cambridge', 'Natural Sciences (Biological)', 'Mathematics 1', 'Biology', 'Chemistry', 'Recommended for Biological Natural Sciences'),
    ('cam_chemeng', 'University of Cambridge', 'Chemical Engineering and Biotechnology', 'Mathematics 1', 'Chemistry', 'Mathematics 2', 'Mathematics 2 or Physics accepted for 3rd module'),
    ('cam_vet', 'University of Cambridge', 'Veterinary Medicine', 'Mathematics 1', 'Biology', 'Chemistry', 'Compulsory module set for Veterinary applicants'),
    ('imp_aero', 'Imperial College London', 'Aeronautical Engineering', 'Mathematics 1', 'Mathematics 2', 'Physics', 'Required combination for Imperial Aeronautics'),
    ('imp_mech', 'Imperial College London', 'Mechanical Engineering', 'Mathematics 1', 'Mathematics 2', 'Physics', 'Required combination for Imperial Mechanical Engineering'),
    ('imp_phys', 'Imperial College London', 'Physics', 'Mathematics 1', 'Mathematics 2', 'Physics', 'Required combination for Imperial Physics')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.esat_course_requirements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select from esat_course_requirements" ON public.esat_course_requirements;
CREATE POLICY "Allow public select from esat_course_requirements" ON public.esat_course_requirements FOR SELECT USING (true);


-- 6. Add ESAT Access Permission Columns to Shared Profiles Table Safely (Locked by Default)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='has_esat_access') THEN
        ALTER TABLE public.profiles ADD COLUMN has_esat_access BOOLEAN DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='has_esat_diagnostic_access') THEN
        ALTER TABLE public.profiles ADD COLUMN has_esat_diagnostic_access BOOLEAN DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='has_esat_topic_access') THEN
        ALTER TABLE public.profiles ADD COLUMN has_esat_topic_access BOOLEAN DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='has_esat_mock_access') THEN
        ALTER TABLE public.profiles ADD COLUMN has_esat_mock_access BOOLEAN DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='has_esat_fullmock_access') THEN
        ALTER TABLE public.profiles ADD COLUMN has_esat_fullmock_access BOOLEAN DEFAULT false;
    END IF;
END $$;

-- Optional Unique index on email to support upsert with on_conflict=email
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);
